### ISSUE TITLE
Custom Application names

### ISSUE THREAD

**Issue by jisnardo** [coroot/coroot#135]
Hi, our k8s PaaS names our deployments like **kd-111205-5e90c9fa-e39feabb-deployment** and inside the manifests adds metadata.annotations and/or metadata.labels that give the sense of the application deployed.

Could be possible to set a custom applicaction name composed by that info?

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "563"
    kpaas/component.domain: test.com
    kpaas/component.name: app
    kpaas/component.version: 9.1.11
    kpaas/deployment.domain: devel
    kpaas/deployment.name: gapp
    kpaas/owner: devel
    kpaas/role: app00
    kpaas/service.domain: test.com
    kpaas/service.name: app
    kpaas/service.version: 30.0.0
    kpaas/translations: '{"k-2f6e1093":"app","k-700b652f":"prometheuscs","k-7c3044cd":"appcs"}'
  creationTimestamp: "2023-02-20T12:51:00Z"
  generation: 589
  labels:
    kpaas/component.domain: a0262a2b
    kpaas/component.name: 2f6e1093
    kpaas/component.version: a41e6ca7
    kpaas/controller: deploymentcontroller
    kpaas/deployment.domain: 2d93289d
    kpaas/deployment.id: kd-125052-7a101811
    kpaas/deployment.name: f209fbf9
    kpaas/owner: 2d93289d
    kpaas/role: cb30c12b
    kpaas/service.domain: a0262a2b
    kpaas/service.name: d5430443
    kpaas/service.version: 4f9e51e4
...
```

Thanks
