### ISSUE TITLE
VictoriaMetrics instead of Prometheus

### ISSUE THREAD

**Issue by fenio** [coroot/coroot#177]
Would be great to see some docs how to use VictoriaMetrics instead of Prometheus.
I've simply switched prometheus url to http://vmsingle-vm:8429 and Coroot is happy showing that Prometheus works but it didn't even show workloads running on the cluster. It also says all nodes are down.

Can you please provide some info what exactly needs to be provided but Prometheus replacement?

**Comment by kirillyu** [comment]
We use coroot with victoriametrics without problems

**Comment by fenio** [comment]
@kirillyu thanks for reply
Did you have to somehow change VM configuration to make it working with Coroot?
I'm still digging into this and it seems that VM drops some labels that Coroot really would like to see.

E0324 16:20:44.957786       1 k8s.go:90] invalid 'kube_pod_info' metric: 'uid' label is empty

**Comment by def** [comment]
@fenio Yes, Coroot expects the `uid` label of the`kube_pod_info` metric. Additionally, please ensure that the VM has discovered the endpoints of `coroot-node-agent` and successfully scrapes them.

**Comment by fenio** [comment]
VM discovered these endpoints and it's scrapping them successfully.
But what's the easiest way to force VM to stop dropping that uid label from metrics?
I'm using default scrape_config configuration... do I have to make my own copy of it and remove all labeldrop instances referencing uid? Sounds crazy.

**Comment by fenio** [comment]
So in case someone is using victoria-metrics-k8s-stack helm chart to install VictoriaMetrics then its scraping configuration needs to be modified like this to make Coroot happy:
```
    kube-state-metrics:
      vmServiceScrape:
        spec:
          endpoints:
          - port: http
            honorLabels: true
            metricRelabelConfigs:
              - action: labeldrop
                regex: (container_id|image_id)
```

https://github.com/fenio/homelab/blob/main/cluster/apps/monitor/victoria-metrics/app/helmrelease.yaml#L69
