### ISSUE TITLE
Node Agent is configured but the coroot is not identifying 

### ISSUE THREAD

**Issue by danilouchoa** [coroot/coroot#2]
I have a problem, even configuring node-agent the coroot is not working and collecting node metrics. Below is the YAML files. Basically I implemented it in the default, I'm also using kube-prometheus-stack but I don't use the podSelector configuration

<img width="214" alt="image" src="https://user-images.githubusercontent.com/15352233/191043618-bf4802eb-7a30-4359-8f45-61896f8fb512.png">

As pictured above, the configuration with promtheus is OK.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/15352233/191043760-00d75c95-2ff9-4abf-93c7-d785d92daa8c.png">

The agent node daemon sets are apparently healthy too but looking into coroot web UI always show `coroot-node-agent : no agent installed`

I've followed the document below to install node-agent

https://coroot.com/docs/metric-exporters/node-agent/overview

```
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: coroot-node-agent
  name: coroot-node-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: coroot-node-agent
  template:
    metadata:
      labels:
        app: coroot-node-agent
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
    spec:
      tolerations:
        - operator: Exists
      hostPID: true
      containers:
        - name: coroot-node-agent
          image: ghcr.io/coroot/coroot-node-agent:latest
          args: ["--cgroupfs-root", "/host/sys/fs/cgroup"]
          ports:
            - containerPort: 80
              name: http
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/sys/fs/cgroup
              name: cgroupfs
              readOnly: true
            - mountPath: /sys/kernel/debug
              name: debugfs
              readOnly: false
      volumes:
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroupfs
        - hostPath:
            path: /sys/kernel/debug
          name: debugfs
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: coroot-node-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: coroot-node-agent
  podMetricsEndpoints:
    - port: http
```

**Comment by danilouchoa** [comment]
hey @def , 

Promtheus did not find targets for corot

<img width="359" alt="image" src="https://user-images.githubusercontent.com/15352233/191048368-e1ccb01e-67af-4952-974a-b90526cceb03.png">


I've created the PodMonitor 

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: coroot-node-agent
  namespace: coroot
spec:
  selector:
    matchLabels:
      app: coroot-node-agent
  podMetricsEndpoints:
    - port: http
```

In my prometheus configuration I am allowing prometheus to see all PodMonitor using as below


<img width="270" alt="image" src="https://user-images.githubusercontent.com/15352233/191048780-a41ffa87-61a3-48f9-b376-125b92593c10.png">
