### ISSUE TITLE
Coroot could not start pyroscope.

### ISSUE THREAD

**Issue by gecube** [coroot/coroot#257]
Hello!

I installed coroot with embedded pyroscope ~163 days ago.
Now I am observing the next:

```
kubectl get pods -n coroot                                            
NAME                                              READY   STATUS             RESTARTS            AGE
coroot-7f75b646f6-9b5xn                           1/1     Running            0                   74d
coroot-clickhouse-shard0-0                        1/1     Running            0                   74d
coroot-node-agent-29hrx                           1/1     Running            0                   28m
coroot-node-agent-4p7ff                           1/1     Running            0                   35m
coroot-node-agent-5g7dp                           1/1     Running            0                   28m
coroot-node-agent-5rfd6                           1/1     Running            0                   28m
coroot-node-agent-5vkhl                           1/1     Running            0                   32m
coroot-node-agent-88255                           1/1     Running            0                   28m
coroot-node-agent-8ngr5                           1/1     Running            0                   28m
coroot-node-agent-cmtfh                           1/1     Running            0                   28m
coroot-node-agent-dmfdj                           1/1     Running            0                   32m
coroot-node-agent-dngng                           1/1     Running            0                   74d
coroot-node-agent-fp4cb                           1/1     Running            0                   33m
coroot-node-agent-j2j52                           1/1     Running            0                   41m
coroot-node-agent-j8mqb                           1/1     Running            0                   41m
coroot-node-agent-jbbwz                           1/1     Running            0                   28m
coroot-node-agent-jlnkt                           1/1     Running            0                   28m
coroot-node-agent-jphkh                           1/1     Running            0                   28m
coroot-node-agent-k8jpn                           1/1     Running            3 (22h ago)         3d20h
coroot-node-agent-kjkhv                           1/1     Running            0                   42m
coroot-node-agent-ljtg7                           1/1     Running            0                   28m
coroot-node-agent-lnccc                           1/1     Running            1 (17h ago)         40h
coroot-node-agent-ltwwr                           1/1     Running            0                   28m
coroot-node-agent-mv4h4                           1/1     Running            0                   53d
coroot-node-agent-pkn97                           1/1     Running            0                   33m
coroot-node-agent-qlp5l                           1/1     Running            0                   74d
coroot-node-agent-qpkt5                           1/1     Running            0                   17h
coroot-node-agent-rjkcp                           1/1     Running            0                   32m
coroot-node-agent-tpkxf                           1/1     Running            0                   74d
coroot-node-agent-v5d69                           1/1     Running            0                   33m
coroot-node-agent-x5f89                           1/1     Running            0                   33m
coroot-node-agent-xt425                           1/1     Running            0                   35m
coroot-node-agent-zlgvm                           1/1     Running            0                   74d
coroot-node-agent-zqhr6                           1/1     Running            0                   41m
coroot-opentelemetry-collector-6c85f55b44-87rhv   1/1     Running            3036 (66s ago)      74d
coroot-pyroscope-df884bb79-29vs2                  0/1     CrashLoopBackOff   20967 (3m16s ago)   74d
```

Everything is working fine for the exception of pyroscope.

```
kubectl describe -n coroot pod/coroot-pyroscope-df884bb79-29vs2 
Name:             coroot-pyroscope-df884bb79-29vs2
Namespace:        coroot
Priority:         0
Service Account:  coroot-pyroscope
Node:             cl1ibdovrsrh5nb9htrd-anej/10.129.0.43
Start Time:       Wed, 27 Mar 2024 18:51:09 +0100
Labels:           app.kubernetes.io/instance=coroot
                  app.kubernetes.io/name=pyroscope
                  pod-template-hash=df884bb79
Annotations:      checksum/config: 550489f848eaa5eb885de439b98d7d8dbb56909a71caa6c27280fcc9b4b8bd7a
Status:           Running
IP:               10.112.175.27
IPs:
  IP:           10.112.175.27
Controlled By:  ReplicaSet/coroot-pyroscope-df884bb79
Containers:
  pyroscope:
    Container ID:  containerd://1fa8224ca54a09ab0079227ea8ec3ffda1b99cabd4c3c346e768bf952870b158
    Image:         pyroscope/pyroscope:0.37.2
    Image ID:      docker.io/pyroscope/pyroscope@sha256:dbca95a15bc1af46b25eb85f417934dcd78f2e0bbe2037aa52b92cb3b0d391ff
    Port:          4040/TCP
    Host Port:     0/TCP
    Args:
      server
      -config
      /tmp/config.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 10 Jun 2024 09:21:53 +0200
      Finished:     Mon, 10 Jun 2024 09:21:54 +0200
    Ready:          False
    Restart Count:  20967
    Liveness:       http-get http://:4040/healthz delay=30s timeout=30s period=15s #success=1 #failure=3
    Readiness:      http-get http://:4040/healthz delay=30s timeout=30s period=5s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /tmp/config.yaml from config (rw,path="config.yaml")
      /var/lib/pyroscope from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ff5vm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coroot-pyroscope
    Optional:  false
  storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  coroot-pyroscope
    ReadOnly:   false
  kube-api-access-ff5vm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                       From     Message
  ----     ------   ----                      ----     -------
  Warning  BackOff  2m32s (x523351 over 74d)  kubelet  Back-off restarting failed container pyroscope in pod coroot-pyroscope-df884bb79-29vs2_coroot(58bafcc2-0e51-4894-a77d-db8717eaa1a3)
```

```
kubectl logs -n coroot coroot-pyroscope-df884bb79-29vs2  
Error: could not initialize server: new storage: Cannot write pid file "/var/lib/pyroscope/dicts/LOCK": write /var/lib/pyroscope/dicts/LOCK: no space left on device
```

Sounds very weird. I tried to use coroot many times and every time I begin to get some strange errors. So coroot does not look like ready-to-use solution out-of-the-box and unfortunately I can't recomment it to my customers.

One more details.

Coroot is installed with FluxCD:

```
kubectl get hr -n coroot
NAME     AGE    READY   STATUS
coroot   163d   True    Helm upgrade succeeded for release coroot/coroot.v2 with chart coroot@0.7.4
```

One may see that there was no changes in coroot config.

full manifest:

```
- apiVersion: helm.toolkit.fluxcd.io/v2
  kind: HelmRelease
  metadata:
    name: coroot
    namespace: coroot
  spec:
    chart:
      spec:
        chart: coroot
        reconcileStrategy: ChartVersion
        sourceRef:
          kind: HelmRepository
          name: coroot
        version: 0.7.4
    interval: 1m0s
    values:
      corootCE:
        ingress:
          enabled: false
        persistentVolume:
          storageClassName: yc-network-hdd
      existingPrometheus:
        enabled: true
        node-agent-podmonitor:
          enabled: true
        service:
          serviceName: monitoring-system-promethe-prometheus
          serviceNamespace: monitoring-system
          servicePort: 9090
      nodeAgent:
        enabled: true
      prometheus:
        enabled: false
      pyroscope:
        enabled: true
        persistence:
          enabled: true
          storageClassName: yc-network-hdd
```
