### ISSUE TITLE
After renaming the default project, tracing and profiling cannot work

### ISSUE THREAD

**Issue by fatsolko** [coroot/coroot#389]
When renaming a project from default to something else, tracing and profiling stop working

![image](https://github.com/user-attachments/assets/88815c09-a1e3-4f57-9003-c4f44fe0aa22)

Logs from coroot:
![image](https://github.com/user-attachments/assets/6f37a20b-2405-45ef-9b54-4e6dcb217e0d)
Logs from node-agent:
![image](https://github.com/user-attachments/assets/da1ef875-1fbc-4fc1-8ede-3e165677db2a)

non default values.yaml
```
existingPrometheus:
  enabled: true
  service:
    serviceName: vmselect-vm-infra
    servicePort: 8481/select/0/prometheus
    serviceNamespace: victoria-metrics
  node-agent-podmonitor:
    enabled: false
prometheus:
  enabled: false
```

chart version: 0.16.1
appVersion: "1.6.1"
