### ISSUE TITLE
VictoriaMetrics compatibility

### ISSUE THREAD

**Issue by fatsolko** [coroot/coroot#390]
When setup VM instead Prometheus, got many logs in vmselect
`unsupported path requested: \"/select/0/prometheus/api/v1/write\""}`

non default values.yaml
```
existingPrometheus:
  enabled: true
  service:
    serviceName: vmselect-vm-infra
    servicePort: 8481/select/0/prometheus
    serviceNamespace: victoria-metrics
  node-agent-podmonitor:
    enabled: false
prometheus:
  enabled: false
```

chart version: 0.16.1
appVersion: "1.6.1"
