### ISSUE TITLE
Automating Coroot Setup with Ansible – API Key Generation or Bootstrap Key Configuration

### ISSUE THREAD

**Issue by Mehdi-BR** [coroot/coroot#457]
Hello,

I have set up Coroot in a VM using Docker Compose, and the agents are deployed in my Kubernetes cluster using the Coroot "**AgentsOnly**" setup. The current configuration works fine after manually providing the Coroot URL and API key.

To automate this monitoring setup using Ansible, I am exploring options to programmatically configure the API key. Specifically:

**- API Key Generation via Coroot's API** : Is there a way to generate an API key by communicating with Coroot's API? If so, could you provide documentation or an example of how this can be achieved?
**- Bootstrap API Key** : If generating an API key dynamically is not supported, is there a way to preconfigure or set a bootstrap API key during the initial setup of Coroot? This would allow me to include the key in my Ansible playbook for seamless deployment.

Any guidance or recommendations on automating this process would be greatly appreciated. Please let me know if additional details are needed to clarify my requirements.

Thank you! 😄

**Comment by apetruhin** [comment]
You can define `projects` and their API keys via [configuration file](https://docs.coroot.com/configuration/configuration/#configuration-file):
```yaml
projects:
  - name: production
    api_keys:
       - key: "5CBC9FE3-91D6-4323-8D18-9D9D64C854DB"
         description: "production cluster"
```

Then, you can configure [Coroot Custom Resource](https://docs.coroot.com/installation/k8s-operator#coroot-cr-custom-resource) to use the API key:
```yaml
agentsOnly:
  corootURL: <coroot URL>
apiKey: "5CBC9FE3-91D6-4323-8D18-9D9D64C854DB"
```
