### ISSUE TITLE
url http://coroot-coroot:8080/v1/metrics server returned HTTP status 404 Not Found

### ISSUE THREAD

**Issue by rmn-lux** [coroot/coroot#464]
Hello! I installed Coroot-operator and coroot-ce via helm from scratch. All pods up&running, but in UI error - coroot-node-agent: no agent installed. Error log from agents in attach. 

Manual request via curl on coroot-coroot:8080 works, but i dont understand what is the problem. 
 
coroot-ce values.yaml, changed only image repo from public to private
```
apiKey:
metricsRefreshInterval: 15s
authAnonymousRole: Admin
authBootstrapAdminPassword:

replicas: 1

service:

communityEdition: 
  image: 
    name: docker-ghcr-remote.domain.ru/coroot/coroot:1.8.4

nodeAgent:
  image:
    name: docker-ghcr-remote.domain.ru/coroot/coroot-node-agent:1.23.10

clusterAgent: 
  image: 
    name: docker-ghcr-remote.domain.ru/coroot/coroot-cluster-agent:1.1.4
  kubeStateMetrics:
    image: 
      name: docker-registry.domain.ru/kube-state-metrics/kube-state-metrics:v2.15.0

externalPrometheus:
  url: http://kube-prometheus-prometheus.prometheus:9090

clickhouse: 
  shards: 1
  replicas: 1
  resources:
  storage:
    size: 10Gi
    className: "csi-sc-cinderplugin"
    reclaimPolicy: Delete # Options: Retain (keeps PVC) or Delete (removes PVC on Coroot CR deletion).
  image: 
    name: docker-registry.domain.ru/clickhouse/clickhouse-server:24.12.4
  keeper: 
    storage:
      size: 10Gi 
      className: "csi-sc-cinderplugin"
    image:
      name: docker-registry.domain.ru/clickhouse/clickhouse-keeper:24.12.4

```

Also tried add this:
```
agentsOnly:
  corootURL: http://coroot-coroot:8080
```

<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/b39a043f-5f0b-42bf-b048-bb9850d6ff17" />

<img width="1415" alt="Image" src="https://github.com/user-attachments/assets/55318393-ea3a-40e5-ad6c-5ef480e633ad" />

<img width="809" alt="Image" src="https://github.com/user-attachments/assets/28da8368-52ed-4ff2-a4f0-c764719999b8" />

<img width="869" alt="Image" src="https://github.com/user-attachments/assets/1356c9ca-e4a3-4938-a63e-ef8bc75765f6" />

<img width="1128" alt="Image" src="https://github.com/user-attachments/assets/4200a90d-e3ab-4901-859f-48e78368f987" />
