### ISSUE TITLE
Prometheus Cache Warning and UI Display Issue

### ISSUE THREAD

**Issue by Gakhramanzode** [coroot/coroot#491]
When opening the Coroot UI, I frequently see a warning message:
> Prometheus cache is 1 day behind (this could be expected after a restart/upgrade)
![Image](https://github.com/user-attachments/assets/d22d9f76-5a4a-4348-ad0c-8648e5c4dcc3)

It's unclear what causes this issue and how to resolve it properly. Additionally, the UI settings contain a similar message:
> Prometheus cache is 1 day behind (this could be expected after a restart/upgrade) Please wait until...
![Image](https://github.com/user-attachments/assets/2caf866c-6f14-4125-8122-ea18c87fa37c)
However, due to a potential frontend issue, the "Please wait until..." part does not display the actual wait time.

The only workaround that helps me is restarting the pod:
```bash
kubectl rollout restart sts coroot-coroot
```

Expected Behavior:
The UI should provide clear guidance on how long to wait or how to fix the issue.
If the cache delay is normal after a restart, it should recover automatically without requiring a manual pod restart.

Coroot Custom Resource:
```yaml
apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
  namespace: coroot
spec:
#  metricsRefreshInterval: 15s # Specifies the metric resolution interval.
  cacheTTL: 24h # Duration for which Coroot retains the metric cache.
...
```
ClickHouse set 24h a retention policy for tables.

Environment:
Coroot version: `ghcr.io/coroot/coroot:1.8.8`

**Comment by def** [comment]
@Gakhramanzode, could you please capture and share the output of `http://COROOT_UI_HOST_AND_PORT/debug/pprof/goroutine?debug=1` when the issue occurs again?

**Comment by Gakhramanzode** [comment]
yes of course

![Image](https://github.com/user-attachments/assets/048754cc-1f2a-43ae-b500-2f0ac8a37f93)

**Comment by KalinaLadnay** [comment]
I have the same problem. Clickhouse retention also set to 24h

**Comment by KalinaLadnay** [comment]
Strange situation. I redeployed coroot and set retention for clickhouse for 2 days and after 1 hour coroot started to work but than it was 1 day retention coroot did not show information about cluster

**Comment by apetruhin** [comment]
@Gakhramanzode,
We have fixed a possible cause of cache synchronization getting stuck. Please update Coroot to version 1.9.1.

If you encounter the issue again, please wait a few minutes to confirm that synchronization is stuck. It is considered stuck if the cache lag does not decrease over time.
<img width="888" alt="Image" src="https://github.com/user-attachments/assets/317bb422-a59e-4856-bb0d-3c823c02f334" />

Before restarting Coroot, please capture its logs and goroutines profile.

**Comment by teksuo** [comment]
Same on 1.4.4, waited for 1 hour already.

I share output of `debug/pprof/goroutine?debug=1` in case it's useful:

```
goroutine profile: total 129
62 @ 0x44228e 0x43aa37 0x46fba5 0x51d307 0x51e5fa 0x51e5e8 0x5d3825 0x5e4305 0x6ed26b 0x674ea3 0x674fd3 0x6f311c 0x4753a1
#	0x46fba4	internal/poll.runtime_pollWait+0x84		/usr/local/go/src/runtime/netpoll.go:343
#	0x51d306	internal/poll.(*pollDesc).wait+0x26		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x51e5f9	internal/poll.(*pollDesc).waitRead+0x279	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x51e5e7	internal/poll.(*FD).Read+0x267			/usr/local/go/src/internal/poll/fd_unix.go:164
#	0x5d3824	net.(*netFD).Read+0x24				/usr/local/go/src/net/fd_posix.go:55
#	0x5e4304	net.(*conn).Read+0x44				/usr/local/go/src/net/net.go:185
#	0x6ed26a	net/http.(*connReader).Read+0x14a		/usr/local/go/src/net/http/server.go:791
#	0x674ea2	bufio.(*Reader).fill+0x102			/usr/local/go/src/bufio/bufio.go:113
#	0x674fd2	bufio.(*Reader).Peek+0x52			/usr/local/go/src/bufio/bufio.go:151
#	0x6f311b	net/http.(*conn).serve+0x75b			/usr/local/go/src/net/http/server.go:2049

39 @ 0x44228e 0x452765 0xee10ed 0x4753a1
#	0xee10ec	github.com/ClickHouse/ch-go/chpool.(*Pool).backgroundHealthCheck+0x8c	/go/pkg/mod/github.com/!click!house/ch-go@v0.61.5/chpool/pool.go:149

3 @ 0x44228e 0x43aa37 0x46fba5 0x51d307 0x51e5fa 0x51e5e8 0x5d3825 0x5e4305 0x70b10a 0x674ea3 0x674fd3 0x70bef9 0x4753a1
#	0x46fba4	internal/poll.runtime_pollWait+0x84		/usr/local/go/src/runtime/netpoll.go:343
#	0x51d306	internal/poll.(*pollDesc).wait+0x26		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x51e5f9	internal/poll.(*pollDesc).waitRead+0x279	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x51e5e7	internal/poll.(*FD).Read+0x267			/usr/local/go/src/internal/poll/fd_unix.go:164
#	0x5d3824	net.(*netFD).Read+0x24				/usr/local/go/src/net/fd_posix.go:55
#	0x5e4304	net.(*conn).Read+0x44				/usr/local/go/src/net/net.go:185
#	0x70b109	net/http.(*persistConn).Read+0x49		/usr/local/go/src/net/http/transport.go:1954
#	0x674ea2	bufio.(*Reader).fill+0x102			/usr/local/go/src/bufio/bufio.go:113
#	0x674fd2	bufio.(*Reader).Peek+0x52			/usr/local/go/src/bufio/bufio.go:151
#	0x70bef8	net/http.(*persistConn).readLoop+0x1b8		/usr/local/go/src/net/http/transport.go:2118

3 @ 0x44228e 0x452765 0x70d8e5 0x4753a1
#	0x70d8e4	net/http.(*persistConn).writeLoop+0xe4	/usr/local/go/src/net/http/transport.go:2435

2 @ 0x44228e 0x452765 0x8d8307 0x4753a1
#	0x8d8306	database/sql.(*DB).connectionOpener+0x86	/usr/local/go/src/database/sql/sql.go:1218

1 @ 0x412dc9 0x4719e9 0x76a1f3 0x4753a1
#	0x4719e8	os/signal.signal_recv+0x28	/usr/local/go/src/runtime/sigqueue.go:152
#	0x76a1f2	os/signal.loop+0x12		/usr/local/go/src/os/signal/signal_unix.go:23

1 @ 0x437011 0x46f77d 0x759f71 0x759da5 0x756846 0x767e48 0x768945 0x6f43e9 0x6f5d02 0xc533e5 0x6f70ce 0x6f2fb4 0x4753a1
#	0x46f77c	runtime/pprof.runtime_goroutineProfileWithLabels+0x1c	/usr/local/go/src/runtime/mprof.go:844
#	0x759f70	runtime/pprof.writeRuntimeProfile+0xb0			/usr/local/go/src/runtime/pprof/pprof.go:734
#	0x759da4	runtime/pprof.writeGoroutine+0x44			/usr/local/go/src/runtime/pprof/pprof.go:694
#	0x756845	runtime/pprof.(*Profile).WriteTo+0x145			/usr/local/go/src/runtime/pprof/pprof.go:329
#	0x767e47	net/http/pprof.handler.ServeHTTP+0x4a7			/usr/local/go/src/net/http/pprof/pprof.go:267
#	0x768944	net/http/pprof.Index+0xe4				/usr/local/go/src/net/http/pprof/pprof.go:384
#	0x6f43e8	net/http.HandlerFunc.ServeHTTP+0x28			/usr/local/go/src/net/http/server.go:2141
#	0x6f5d01	net/http.(*ServeMux).ServeHTTP+0x141			/usr/local/go/src/net/http/server.go:2519
#	0xc533e4	github.com/gorilla/mux.(*Router).ServeHTTP+0x1c4	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
#	0x6f70cd	net/http.serverHandler.ServeHTTP+0x8d			/usr/local/go/src/net/http/server.go:2943
#	0x6f2fb3	net/http.(*conn).serve+0x5f3				/usr/local/go/src/net/http/server.go:2014

1 @ 0x44228e 0x40d58d 0x40d192 0x105cb05 0x4753a1
#	0x105cb04	main.main.func1+0x84	/tmp/src/main.go:100

1 @ 0x44228e 0x40d58d 0x40d1b2 0x100616c 0x4753a1
#	0x100616b	github.com/coroot/coroot/stats.NewCollector.func1+0x6b	/tmp/src/stats/stats.go:142

1 @ 0x44228e 0x40d58d 0x40d1b2 0x1009085 0x4753a1
#	0x1009084	github.com/coroot/coroot/stats.(*Collector).startProcessStatsCollector.func1+0xa4	/tmp/src/stats/stats.go:413

1 @ 0x44228e 0x40d58d 0x40d1b2 0x100cee5 0x4753a1
#	0x100cee4	github.com/coroot/coroot/watchers.Start.func1+0x84	/tmp/src/watchers/watchers.go:30

1 @ 0x44228e 0x40d58d 0x40d1b2 0xb3af66 0x4753a1
#	0xb3af65	k8s.io/klog.(*loggingT).flushDaemon+0x65	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010

1 @ 0x44228e 0x40d58d 0x40d1b2 0xc4ad47 0x4753a1
#	0xc4ad46	github.com/coroot/coroot/notifications.NewIncidentNotifier.func1+0x66	/tmp/src/notifications/incidents.go:21

1 @ 0x44228e 0x40d58d 0x40d1b2 0xe585d6 0x4753a1
#	0xe585d5	github.com/coroot/coroot/cloud-pricing.NewManager.func1+0xb5	/tmp/src/cloud-pricing/manager.go:55

1 @ 0x44228e 0x40d58d 0x40d1b2 0xe7cd73 0x4753a1
#	0xe7cd72	github.com/coroot/coroot/cache.(*Cache).compaction+0x212	/tmp/src/cache/compaction.go:91

1 @ 0x44228e 0x40d58d 0x40d1b2 0xe7d2e5 0x4753a1
#	0xe7d2e4	github.com/coroot/coroot/cache.(*Cache).compaction.func1+0xa4	/tmp/src/cache/compaction.go:82

1 @ 0x44228e 0x40d58d 0x40d1b2 0xe7f0ff 0x4753a1
#	0xe7f0fe	github.com/coroot/coroot/cache.(*Cache).gc+0x13e	/tmp/src/cache/gc.go:16

1 @ 0x44228e 0x40d58d 0x40d1b2 0xe7ff76 0x4753a1
#	0xe7ff75	github.com/coroot/coroot/cache.(*Cache).updater+0x75	/tmp/src/cache/updater.go:33

1 @ 0x44228e 0x40d58d 0x40d1b2 0xfd101d 0x4753a1
#	0xfd101c	github.com/coroot/coroot/collector.New.func1+0x9c	/tmp/src/collector/collector.go:62

1 @ 0x44228e 0x43aa37 0x46fba5 0x51d307 0x51e5fa 0x51e5e8 0x5d3825 0x5e4305 0x6ece37 0x4753a1
#	0x46fba4	internal/poll.runtime_pollWait+0x84		/usr/local/go/src/runtime/netpoll.go:343
#	0x51d306	internal/poll.(*pollDesc).wait+0x26		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x51e5f9	internal/poll.(*pollDesc).waitRead+0x279	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x51e5e7	internal/poll.(*FD).Read+0x267			/usr/local/go/src/internal/poll/fd_unix.go:164
#	0x5d3824	net.(*netFD).Read+0x24				/usr/local/go/src/net/fd_posix.go:55
#	0x5e4304	net.(*conn).Read+0x44				/usr/local/go/src/net/net.go:185
#	0x6ece36	net/http.(*connReader).backgroundRead+0x36	/usr/local/go/src/net/http/server.go:683

1 @ 0x44228e 0x43aa37 0x46fba5 0x51d307 0x5227ec 0x5227da 0x5d5849 0x5ed25e 0x5ec410 0x6f7524 0x6f7191 0x105c3ce 0x105c33b 0x441e1b 0x4753a1
#	0x46fba4	internal/poll.runtime_pollWait+0x84		/usr/local/go/src/runtime/netpoll.go:343
#	0x51d306	internal/poll.(*pollDesc).wait+0x26		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x5227eb	internal/poll.(*pollDesc).waitRead+0x2ab	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x5227d9	internal/poll.(*FD).Accept+0x299		/usr/local/go/src/internal/poll/fd_unix.go:611
#	0x5d5848	net.(*netFD).accept+0x28			/usr/local/go/src/net/fd_unix.go:172
#	0x5ed25d	net.(*TCPListener).accept+0x1d			/usr/local/go/src/net/tcpsock_posix.go:152
#	0x5ec40f	net.(*TCPListener).Accept+0x2f			/usr/local/go/src/net/tcpsock.go:315
#	0x6f7523	net/http.(*Server).Serve+0x363			/usr/local/go/src/net/http/server.go:3061
#	0x6f7190	net/http.(*Server).ListenAndServe+0x70		/usr/local/go/src/net/http/server.go:2990
#	0x105c3cd	net/http.ListenAndServe+0x42ad			/usr/local/go/src/net/http/server.go:3244
#	0x105c33a	main.main+0x421a				/tmp/src/main.go:175
#	0x441e1a	runtime.main+0x2ba				/usr/local/go/src/runtime/proc.go:267

1 @ 0x44228e 0x452765 0xfd50d0 0x4753a1
#	0xfd50cf	github.com/coroot/coroot/collector.NewLogsBatch.func1+0xaf	/tmp/src/collector/logs.go:110

1 @ 0x44228e 0x452765 0xfd7eb0 0x4753a1
#	0xfd7eaf	github.com/coroot/coroot/collector.NewProfilesBatch.func1+0xaf	/tmp/src/collector/profiles.go:93

1 @ 0x44228e 0x452765 0xfda470 0x4753a1
#	0xfda46f	github.com/coroot/coroot/collector.NewTracesBatch.func1+0xaf	/tmp/src/collector/traces.go:130

1 @ 0x44228e 0x472365 0xe807d9 0x4753a1
#	0x472364	time.Sleep+0x124						/usr/local/go/src/runtime/time.go:195
#	0xe807d8	github.com/coroot/coroot/cache.(*Cache).updaterWorker+0x418	/tmp/src/cache/updater.go:192
```

**Comment by Gakhramanzode** [comment]
> [@Gakhramanzode](https://github.com/Gakhramanzode), We have fixed a possible cause of cache synchronization getting stuck. Please update Coroot to version 1.9.1.
> 
> If you encounter the issue again, please wait a few minutes to confirm that synchronization is stuck. It is considered stuck if the cache lag does not decrease over time. <img alt="Image" width="888" src="https://private-user-images.githubusercontent.com/199054/424906042-317bb422-a59e-4856-bb0d-3c823c02f334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI0Nzk0NDksIm5iZiI6MTc0MjQ3OTE0OSwicGF0aCI6Ii8xOTkwNTQvNDI0OTA2MDQyLTMxN2JiNDIyLWE1OWUtNDg1Ni1iYjBkLTNjODIzYzAyZjMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyMFQxMzU5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzA4YmViMzc2MzEzMTYxMjNmNThlMjE1Y2ZiYjkzNDNjMTE5ZGY2YmRjYmMyNzczZGZjODA3MjlkYWFhZTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.acYKQn9CHmPl1_nfaAq-bNcqnLbd_NiRG-ytiomPHfI">
> 
> Before restarting Coroot, please capture its logs and goroutines profile.

hello!

thanks. I'll try it update Coroot to version 1.9.1. and give you feedback.

**Comment by Gakhramanzode** [comment]
@apetruhin @def we encounter the issue again :( 
![Image](https://github.com/user-attachments/assets/a14f1dcc-6aa5-4558-8937-3b2f76a347c2)

goroutines profile:
![Image](https://github.com/user-attachments/assets/2b53eb1b-0682-4294-82b3-720b60769a09)

I have attached the logs file to the message
[coroot-coroot-0.log](https://github.com/user-attachments/files/19445230/coroot-coroot-0.log)

coroot/coroot:1.9.1

**Comment by def** [comment]
@Gakhramanzode, what type of volume are you using for the Coroot StatefulSet? It looks like another process might be accessing the same volume. Could you please share more details about your setup?

**Comment by Gakhramanzode** [comment]
@def we user nfs-server:
```yaml
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nfs-pv-0
    spec:
      capacity:
        storage: 50Gi
      accessModes:
        - ReadWriteMany
        - ReadWriteOnce
      nfs:
        server: share.vm.tech
        path: "/data/coroot/prod/main"
      persistentVolumeReclaimPolicy: Retain
```

**Comment by def** [comment]
Each Coroot instance requires exclusive access to a dedicated volume

**Comment by def** [comment]
How many Coroot replicas are running in each cluster?

**Comment by def** [comment]
Something's wrong here. Based on the log you provided, we can clearly see that the instance is starting from scratch — it created a cache directory for the project. Then, we see that some cache files were deleted by another process.

**Comment by Gakhramanzode** [comment]
`cacheTTL` configuration:
infra-prod 
```yaml
  - apiVersion: coroot.com/v1
    kind: Coroot
    metadata:
      name: coroot
      namespace: coroot
    spec:
    #  metricsRefreshInterval: 15s # Specifies the metric resolution interval.
      cacheTTL: 72h # Duration for which Coroot retains the metric cache.
```
main-prod
```yaml
 - apiVersion: coroot.com/v1
    kind: Coroot
    metadata:
      name: coroot
      namespace: coroot
    spec:
    #  metricsRefreshInterval: 15s # Specifies the metric resolution interval.
      cacheTTL: 24h # Duration for which Coroot retains the metric cache
```

**Comment by def** [comment]
Probably, the issue is that your Coroot instances in different clusters are sharing the same Postgres database for configuration

**Comment by Gakhramanzode** [comment]
no, we using different Postgres database:
main-prod
```yaml
    # Store configuration in a Postgres DB instead of SQLite (required if replicas > 1).
      postgres:
        host: 192.168.128.191 # Postgres host or service name.
        port: 5000 # Postgres port (optional, default 5432).
        database: coroot-main-prod # Name of the database.
        user: coroot-main-prod # Username for accessing Postgres.
    #    password: # Password for accessing postgres (plain-text, not recommended).
        passwordSecret: # Secret containing password.
          name: coroot-custom-resource-env # Name of the secret to select from.
          key: postgres-secret # Key of the secret to select from.
        params: # Extra parameters, e.g., sslmode and connect_timeout.
          sslmode: disable
          binary_parameters: "yes"
```

infra-prod
```yaml
    # Store configuration in a Postgres DB instead of SQLite (required if replicas > 1).
      postgres:
        host: 192.168.128.191 # Postgres host or service name.
        port: 5000 # Postgres port (optional, default 5432).
        database: coroot-infra-prod # Name of the database.
        user: coroot-infra-prod # Username for accessing Postgres.
    #    password: # Password for accessing postgres (plain-text, not recommended).
        passwordSecret: # Secret containing password.
          name: coroot-custom-resource-env # Name of the secret to select from.
          key: postgres-secret # Key of the secret to select from.
        params: # Extra parameters, e.g., sslmode and connect_timeout.
          sslmode: disable
          binary_parameters: "yes"
```
