### ISSUE TITLE
could not disable authentication

### ISSUE THREAD

**Issue by gecube** [coroot/coroot#493]
Good day!

I noticed very peculiar issue.

There was a namespace Coroot. Where Coroot-operator and Coroot (old installation without operator) were found. I removed Coroot. And prepared the next manifest:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coroot
spec:
  interval: 1h
  chart:
    spec:
      chart: coroot-ce
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: coroot
  values:
    authAnonymousRole: Admin
    clickhouse:
      replicas: 1
      shards: 1
      storage:
        size: 100Gi
    metricsRefreshInterval: 15s
    prometheus:
      storage:
        size: 100Gi
    storage:
      size: 100Gi
```

My expectations:

I would get Coroot installation w/o authentication.

I checked the manifests - the operator works like it was designed and it created Coroot pod with:

```yaml
...
      env:
        - name: GLOBAL_REFRESH_INTERVAL
          value: 15s
        - name: INSTALLATION_TYPE
          value: k8s-operator
        - name: AUTH_ANONYMOUS_ROLE
          value: Admin
        - name: GLOBAL_PROMETHEUS_URL
          value: 'http://coroot-prometheus.coroot:9090'
        - name: GLOBAL_CLICKHOUSE_ADDRESS
          value: 'coroot-clickhouse.coroot:9000'
        - name: GLOBAL_CLICKHOUSE_USER
          value: default
        - name: GLOBAL_CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coroot-clickhouse
              key: password
        - name: GLOBAL_CLICKHOUSE_INITIAL_DATABASE
          value: default
...
``` 

I checked - the pvc were not picked up from the old installation, they are brand new. And I am getting starting page of coroot asking for a password of admin:

<img width="1207" alt="Image" src="https://github.com/user-attachments/assets/4a476b78-39db-46ec-9747-f8a39bb45ef1" />

I believe there is an issue with `AUTH_ANONYMOUS_ROLE` when k8s installation mode
