### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by miran248** [coroot/coroot#517]
Hey,

Coroot went down a few hours ago, any ideas what could be the cause?

These logs are from `coroot-coroot-0`, all other deployments are up and running, with no errors.
```
coroot I0328 19:29:30.089722       1 main.go:42] version: 1.9.8                                                                                   
coroot I0328 19:29:30.089926       1 main.go:56] database type: sqlite                                                                            
coroot I0328 19:29:34.056102       1 cache.go:136] loaded from disk in 3.961s                                                                     
coroot I0328 19:29:34.056444       1 compaction.go:81] compaction worker started                                                                  
coroot I0328 19:29:34.252249       1 main.go:191] listening on :8080                                                                              
coroot I0328 19:29:35.599865       1 migration.go:45] clickhouse tables migration done in 1.543s                                                  
coroot panic: runtime error: invalid memory address or nil pointer dereference                                                                    
coroot [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xe2606f]                                                                    
coroot                                                                                                                                            
coroot goroutine 170 [running]:                                                                                                                   
coroot github.com/coroot/coroot/constructor.(*Constructor).getInstanceByAppId(0x1385480?, 0xc0000503a0, {0xc001bf13c5, 0x17})                     
coroot     /tmp/src/constructor/containers.go:44 +0x14f                                                                                           
coroot github.com/coroot/coroot/constructor.(*Constructor).loadContainers.func1({0x14fc6c6?, 0xc00004ffa0?}, 0xc00004fd70)                        
coroot     /tmp/src/constructor/containers.go:157 +0xff                                                                                           
coroot github.com/coroot/coroot/constructor.(*Constructor).loadContainers.func17(...)                                                             
coroot     /tmp/src/constructor/containers.go:269                                                                                                 
coroot github.com/coroot/coroot/constructor.(*Constructor).loadContainers(0xc00186f920, 0xc0002c4d80, 0xc00186fb00, 0xc000050b08, 0xc000050988, 0x
c0000510c0, 0xc0000512c0, 0xc0000511c0)                                                                                                           
coroot     /tmp/src/constructor/containers.go:276 +0x66b                                                                                          
coroot github.com/coroot/coroot/constructor.(*Constructor).LoadWorld.func14()                                                                     
coroot     /tmp/src/constructor/constructor.go:101 +0x36                                                                                          
coroot github.com/coroot/coroot/constructor.(*Profile).stage(0xc0001158a8?, {0x14da610?, 0x67e6d5f9?}, 0x10000000027?)                            
coroot     /tmp/src/constructor/stats.go:122 +0x124                                                                                               
coroot github.com/coroot/coroot/constructor.(*Constructor).LoadWorld(0xc00186f920, {0x2774990, 0x30d67e0}, 0x67e6d3b0, 0x67e6d5f9, 0xf, 0x0)      
coroot     /tmp/src/constructor/constructor.go:101 +0xda8                                                                                         
coroot github.com/coroot/coroot/cache.(*Cache).processRecordingRules(0xc0002c4680, 0x67e6f87c, 0xc002504480, 0xf, 0xc0024781e0)                   
coroot     /tmp/src/cache/updater.go:320 +0x416                                                                                                   
coroot github.com/coroot/coroot/cache.(*Cache).updaterWorker(0xc0002c4680, 0xc000058020, {0xc00250c978, 0x8}, 0xc00080a5a0)                       
coroot     /tmp/src/cache/updater.go:188 +0x894                                                                                                   
coroot created by github.com/coroot/coroot/cache.(*Cache).updater in goroutine 20                                                                 
coroot     /tmp/src/cache/updater.go:49 +0x345
```

I upgraded `coroot-operator` chart from `0.2.1` to `0.2.10` 10 minutes ago but it made no difference.
`coroot-prometheus` is reporting `Out of order sample from remote write` from time to time.

Thanks!

**Comment by miran248** [comment]
Minutes before it went down i changed `architecture` from `replication` to `standalone` on `redis` chart (`registry-1.docker.io/bitnamicharts`, version `20.6.3`), which essentially redeployed everything but names remained mostly the same, so i guess this could be the cause.

**Comment by miran248** [comment]
Before

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.6.3
    helm:
      releaseName: redis
      values: |
        architecture: replication
        auth:
          enabled: false
        master:
          count: 1
          disableCommands: []
          resourcesPreset: none
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          persistence:
            enabled: true
            size: 1Gi
        sentinel:
          enabled: true
          masterSet: redis
          masterService:
            enabled: true
          resourcesPreset: none
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          persistence:
            enabled: true
            size: 1Gi
        replica:
          automountServiceAccountToken: true
          resourcesPreset: none
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        rbac:
          create: true
        metrics:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
```

After
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.6.3
    helm:
      releaseName: redis
      values: |
        architecture: standalone
        auth:
          enabled: false
        master:
          count: 1
          disableCommands: []
          resourcesPreset: none
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          persistence:
            enabled: true
            size: 1Gi
        rbac:
          create: true
        metrics:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
```
