### ISSUE TITLE
More operator/agent flexibility

### ISSUE THREAD

**Issue by rlex** [coroot/coroot#528]
Hello, we wanted to use coroot for service maps and performance metrics.
Right now, if deployed with operator, it will include all functionality (traces+metrics+profiles) without ability to disable any of them.

Additionally, right now there is only two options for installing bundled DBs (prometheus and clickhouse) - either global external or bundled ones, which locks relevant ENV variables behind 2 pre-defined options.
It will be nice if we can install coroot the old way (which was possible year or so ago?) - install coroot main app only on some central cluster, deploy agents only (this seems to be already possible with agentsOnly directive?) and then create projects manually specifying their prometheus/clickhouse server addresses, so it will reuse existing metrics configuration in clusters. Right now, as ENV variables can't be overriden, it's locked behind addresses specified in GLOBAL_* env variables.

**Comment by apetruhin** [comment]
Starting with Operator [v1.3.0](https://github.com/coroot/coroot-operator/releases/tag/v1.3.0), logs/profiles/traces collection can be disabled via the [Coroot Custom Resource](https://docs.coroot.com/installation/k8s-operator#coroot-cr-custom-resource):
```yaml
nodeAgent:
  logCollector:
    collectLogBasedMetrics: true # Collect log-based metrics. Disables `collectLogEntries` if set to false.
    collectLogEntries: true      # Collect log entries and store them in ClickHouse.
  ebpfTracer:
    enabled: true # Collect traces and store them in ClickHouse.
  ebpfProfiler:
    enabled: true # Collect profiles and store them in ClickHouse.
```
