### ISSUE TITLE
multiple restarts on coroot-coroot-0

### ISSUE THREAD

**Issue by 404notfoundhard** [coroot/coroot#608]
During the first deployment, coroot-coroot-0 is constantly restarted, and it starts working stably after about 2-3 minutes.

If you update or add a project, the duration of such restarts reaches 5-7 minutes.
How to reproduce:
coroot/coroot-operator: 0.4.1
coroot/coroot-ce: 0.3.1

```yml
apiKeySecret:
  name: coroot
  key:  apiKeyInfra

projects:
  - name: infra
    apiKeys:
      - description: infra
        keySecret:
          name: coroot
          key:  apiKeyInfra

  - name: staging
    apiKeys:
      - description: staging
        keySecret:
          name: coroot
          key:  apiKeyStaging

  - name: dev
    apiKeys:
      - description: dev
        keySecret:
          name: coroot
          key:  apiKeyDev
```

each restart is accompanied by such a line of the log in the operator:
```
2025-06-25T10:38:50Z	ERROR	failed to create or update	{"namespace": "coroot", "name": "coroot-coroot", "type": "*v1.StatefulSet", "error": "Operation cannot be fulfilled on statefulsets.apps \"coroot-coroot\": the object has been modified; please apply your changes to the latest version and try again"}
2025-06-25T10:38:51Z	ERROR	failed to create or update	{"namespace": "coroot", "name": "coroot-coroot", "type": "*v1.StatefulSet", "error": "Operation cannot be fulfilled on statefulsets.apps \"coroot-coroot\": the object has been modified; please apply your changes to the latest version and try again"}
```
