### ISSUE TITLE
Coroot operator takes control of third-party secrets

### ISSUE THREAD

**Issue by 404notfoundhard** [coroot/coroot#609]
In the coroot functionality says that you can specify an api key from a third-party secret. 
In order not to show the keys when deploying, I keep them secret through the universal chart. 
However, when I add a project to the webUI, the operator intercepts the control of this secret.

As a result, helm upgrades are not possible(secrets), cuz are not controlled by the chart.

**Comment by apetruhin** [comment]
Please provide more details to help us reproduce the issue.
Could you clarify what you mean by "universal chart" and share the error you get during the Helm upgrade?

**Comment by 404notfoundhard** [comment]
Step to reproduce:
1. Create helm release with only one entity - "secrets" (I'm using the nyxis universal chart, but a heavily modified one is suitable for testing. You can also create a secret yourself.), for instance secret name - "coroot-secrets" 
2. kubectl -n coroot_ns get secrets  coroot-secrets -o yaml
```yml
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-999"
  creationTimestamp: "2025-06-27T07:26:38Z"
  labels:
    app.kubernetes.io/instance: coroot-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coroot-secrets
    helm.sh/chart: universal-chart-0.14.6
```
3.  Next, this secret is used in a structure such as "projects" and the apiKeySecret variable.
4.  After starting coroot, you need to add a new project via webui.
5. 2. kubectl -n coroot_ns get secrets  coroot-secrets -o yaml
```yml
  labels:
    app.kubernetes.io/component: coroot
    app.kubernetes.io/managed-by: coroot-operator
```


But now I've checked and the secret is no longer intercepted by coroot, which is very strange. The operator's version has not changed. 
I'll reopen the issue later if it happens again.
