### ISSUE TITLE
Cluster agent can't send the data to coroot, when it is described in the projects.

### ISSUE THREAD

**Issue by 404notfoundhard** [coroot/coroot#610]
Problem:
Coroot deployed in the "Infra" cluster, I described this cluster in projects and specified the api key from a third-party secret, both in projects and in apiKeySecret.  But for some reason, the cluster agent can't send the data to coroot-coroot, as if the key is wrong.

Sys info:
coroot/coroot-operator: 0.4.1
coroot/coroot-ce: 0.3.1

Config:
```yml
prometheus: null
clickhouse: null

# authAnonymousRole: Viewer

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  host: coroot.some.corp
  path: /
  tls:
    secretName: null
    hosts:
      - coroot.some.corp

service:
  type: LoadBalancer
  port: 80
  annotations:
    io.cilium/lb-ipam-ips: 172.16.22.85
    io.cilium/lb-ipam-sharing-key: "coroot"

externalClickhouse:
  address: clickhouse.coroot.svc:9000
  database: default
  user: default
  passwordSecret:
    name: coroot-click-secret
    key: clickhouse_pass

externalPrometheus:
  url: "http://vmselect.coroot.svc:8481/select/0/prometheus"
  remoteWriteURL: "http://vminsert.coroot.svc:8480/insert/0/prometheus"


apiKeySecret:
  name: coroot
  key:  apiKeyInfra

storage:
  className: iscsi
  size: 20Gi
  reclaimPolicy: Delete

nodeAgent:
  update_strategy:
    type: "OnDelete"

clusterAgent:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 200Mi


communityEdition:
  image:
    name: ghcr.io/coroot/coroot:1.12.4

projects:
  - name: Infra
    apiKeys:
      - description: infra
        keySecret:
          name: coroot
          key:  apiKeyInfra
```

cluster agent logs:
```
I0625 12:27:25.986303       1 prom.go:217] level warn remote_name 64a5f3 url http://coroot-coroot.coroot:8080/v1/metrics msg Failed to send batch, retrying err Post "http://coroot-coroot.coroot:8080/v1/metrics": dial tcp 172.24.158.137:8080: connect: connection refused
```
cluster agent:
```sh
kubectl -n coroot exec -ti pod/coroot-cluster-agent-55df7589b9-bg666 -c cluster-agent -- bash
bash-5.1$ env | grep API
API_KEY=A-NPF9ktLHpEOdNQkX0dThFyxn22PZij
```

coroot-coroot-0:
```sh
kubectl -n coroot exec -ti coroot-coroot-0 -- bash

bash-5.1$ cat config/config.yaml 
projects:
- apiKeys:
  - description: infra
    key: ${COROOT_CONFIG_SECRET_A89B9AAB}
  name: Infra
bash-5.1$ env | grep COROOT_CONFIG_SECRET_A89B9AAB
COROOT_CONFIG_SECRET_A89B9AAB=A-NPF9ktLHpEOdNQkX0dThFyxn22PZij
```

coroot-coroot-0 logs:
```
E0625 12:51:56.546554       1 traces.go:21] project not found
E0625 12:51:56.546714       1 logs.go:21] project not found
```
