### ISSUE TITLE
unstable work of graph

### ISSUE THREAD

**Issue by Nello-Angelo** [coroot/coroot#72]
![Screenshot_20](https://github.com/coroot/coroot/assets/82488489/6e657c70-186b-40e1-8bcb-39a505c84b71)
![Screenshot_18](https://github.com/coroot/coroot/assets/82488489/7ede843d-9bc6-42a3-90ec-d2762104a230)
![Screenshot_19](https://github.com/coroot/coroot/assets/82488489/45422105-d4fd-45ec-8a61-5e787abf4b91)

unstable work of graph sometimes graphs are vanishing and can`t make full node graph. I use service mesh linkerd

**Comment by Nello-Angelo** [comment]
also there is no distinct separation of topologies by namespaces. The current topology is terrible and awkward to use

**Comment by def** [comment]
@Nello-Angelo, could you please check the Prometheus (VictoriaMetrics) scrape interval for the `coroot-node-agent` targets, as well as the refresh interval configured in Coroot (Settings -> Prometheus)? 
Coroot requires that the refresh interval is not set to a value lower than the scrape interval.

**Comment by Nello-Angelo** [comment]
scrape_interval: 15s 
Refresh interval: 15s

**Comment by def** [comment]
What problem is Coroot showing on the Instances tab?

**Comment by Nello-Angelo** [comment]
![Screenshot_25](https://github.com/coroot/coroot/assets/82488489/333e2ab6-30ce-4fae-b34e-04cde6dc88aa)
![Screenshot_23](https://github.com/coroot/coroot/assets/82488489/4791ad55-db94-4a4d-9be9-470059c3d198)
![Screenshot_24](https://github.com/coroot/coroot/assets/82488489/b7c2b2e8-c47b-4550-9dc4-5bc64f7321c2)

**Comment by Nello-Angelo** [comment]
```
log-level: debug
retention: 8h
retention-levels:
  "0": 1h
  "1": 4h
  "2": 8h
scrape-configs:
- enabled-profiles:
  - cpu
  - mem
  job-name: kubernetes-pods
  kubernetes-sd-configs:
  - role: pod
  relabel-configs:
  - action: keep
    regex: true
    source-labels:
    - __meta_kubernetes_pod_annotation_pyroscope_io_scrape
  - action: replace
    source-labels:
    - __meta_kubernetes_pod_annotation_pyroscope_io_application_name
    target-label: __name__
  - action: replace
    regex: (https?)
    source-labels:
    - __meta_kubernetes_pod_annotation_pyroscope_io_scheme
    target-label: __scheme__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source-labels:
    - __address__
    - __meta_kubernetes_pod_annotation_pyroscope_io_port
    target-label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source-labels:
    - __meta_kubernetes_namespace
    target-label: namespace
  - action: replace
    source-labels:
    - __meta_kubernetes_pod_name
    target-label: pod
  - action: drop
    regex: Pending|Succeeded|Failed|Completed
    source-labels:
    - __meta_kubernetes_pod_phase
  - action: labelmap
    regex: __meta_kubernetes_pod_annotation_pyroscope_io_profile_(.+)
    replacement: __profile_$1
```
